name: winga_kiganjani
description: "WINGA KIGANJANI - Campus Commerce & Financial Inclusion Platform"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.5+1

  # Flutter Localization
  flutter_localizations:
    sdk: flutter

  # Internationalization
  intl: ^0.20.2

  # Save selected language and other local settings
  shared_preferences: ^2.5.5
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  # Required for Flutter localization code generation
  generate: true

  # Material Icons
  uses-material-design: true